# Generated by Django 5.0 on 2023-12-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id_anggota', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], default='L', max_length=1)),
                ('alamat', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telepon', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
