# Generated by Django 5.0 on 2023-12-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='telepon',
            field=models.CharField(max_length=16),
        ),
    ]
