# Generated by Django 4.2.9 on 2024-01-11 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='penerbit',
        ),
        migrations.AlterField(
            model_name='buku',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='penulis',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Penerbit',
        ),
    ]
