# Generated by Django 4.2.9 on 2024-01-03 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0002_alter_anggota_telepon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id_peminjaman', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('tgl_pinjam', models.DateField()),
                ('tgl_kembali', models.DateField()),
                ('id_anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpus.anggota')),
            ],
        ),
    ]
