# Generated by Django 4.2.9 on 2024-01-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0003_peminjaman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peminjaman',
            old_name='id_anggota',
            new_name='anggota',
        ),
    ]
