# Generated by Django 4.2.9 on 2024-01-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0004_alter_buku_rilis'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='slug',
            field=models.CharField(default='books', max_length=255),
        ),
    ]
