# Generated by Django 4.2.9 on 2024-01-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0004_rename_id_anggota_peminjaman_anggota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anggota',
            old_name='id_anggota',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='peminjaman',
            old_name='id_peminjaman',
            new_name='id',
        ),
    ]
