# Generated by Django 4.2.9 on 2024-01-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0005_rename_id_anggota_anggota_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
