# Generated by Django 4.2.9 on 2024-01-09 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0006_alter_anggota_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penerbit',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='tgl_kembali',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='tgl_pinjam',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('rilis', models.DateTimeField()),
                ('penerbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpus.penerbit')),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpus.penulis')),
            ],
        ),
    ]
