# Generated by Django 4.2.9 on 2024-01-20 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0011_alter_user_join_at_notifikasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikasi',
            name='tanggal',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
