# Generated by Django 4.2.9 on 2024-01-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penerbit',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], default='L', max_length=1)),
                ('alamat', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('telepon', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=255)),
                ('petugas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('tgl_pinjam', models.DateTimeField()),
                ('tgl_kembali', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpus.user')),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('rilis', models.DateTimeField()),
                ('penerbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpus.penerbit')),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpus.penulis')),
            ],
        ),
    ]
