# Generated by Django 4.2.9 on 2024-01-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0002_remove_buku_penerbit_alter_buku_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='thumbnail',
            field=models.CharField(default='/media/books/default.png', max_length=255),
        ),
    ]
