# Generated by Django 4.2.9 on 2024-01-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0003_buku_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='rilis',
            field=models.DateTimeField(max_length=100),
        ),
    ]
