# Generated by Django 4.2.9 on 2024-01-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0006_alter_buku_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='deskripsi',
            field=models.TextField(default='Tidak ada deskripsi'),
        ),
    ]
