# Generated by Django 4.2.9 on 2024-01-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0008_peminjaman_buku'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='dikembalikan',
            field=models.BooleanField(default=False),
        ),
    ]
