# Generated by Django 4.2.9 on 2024-01-16 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0009_peminjaman_dikembalikan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='join_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 17, 39, 49, 760237)),
        ),
    ]
