# Generated by Django 4.2.9 on 2024-01-20 06:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0010_user_join_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 20, 6, 53, 10, 940649)),
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('pesan', models.TextField(default='Tidak ada pesan notifikasi')),
                ('tanggal', models.DateTimeField(default=datetime.datetime(2024, 1, 20, 6, 53, 10, 941554))),
                ('dibaca', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpus.user')),
            ],
        ),
    ]
